version: '3.7'

services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - near-taxi-mysql:/var/lib/mysql
  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9410:9410"
      - "9411:9411"
    environment:
      RABBIT_URI: "amqp://guest:guest@rabbit:5672"
    depends_on:
      - rabbit

volumes:
  near-taxi-mysql:
