server:
  port: 8761

spring:
  application:
    name: service-discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
