---
spring:
  profiles: prod

cars:
  counter: 3

server:
  port: 8070

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - hystrix.stream
          - refresh